import Head from 'next/head';
import Script from 'next/script';

import { GeneratePage } from '@/components/pageComponents/GeneratePage';
import { ENV } from '@/utils/getConfig';

export default function Generate() {
  return (
    <>
      {process.env.NODE_ENV === ENV.production && (
        <>
          <Script strategy="afterInteractive" src="https://www.googletagmanager.com/gtag/js?id=G-XWTERQG7KB" />
          <Script id="google-analytics" strategy="afterInteractive">
            {`
              window.dataLayer = window.dataLayer || [];
              function gtag(){dataLayer.push(arguments);}
              gtag('js', new Date());

              gtag('config', 'G-XWTERQG7KB');
            `}
          </Script>
        </>
      )}

      <Head>
        <title>PlatePal - AI Nutritionist</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logos/logo-only.svg" />
      </Head>

      <GeneratePage />
    </>
  );
}
